version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: gaza-market-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: gaza-market-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gaza-market
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: gaza-market-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo_data:
